feat: Provide versions of default applications
mesosphere/kommander-applications pull request #208
Opened 2022-02-22 10:47 UTC by mikolajb

Jira: https://jira.d2iq.com/browse/D2IQ-84235

2022-02-22 18:33 UTC, takirala approved these changes

2022-02-23 13:44 UTC, makkes requested changes

2022-02-23 13:44 UTC, makkes commented on hack/validate-default-apps-versions.sh
> +latestKommanderVersion=$(find services/kommander -maxdepth 1 -type d | sort | tail -1)
this doesn't work:
```
$ ll services/kommander/
total 20K
drwxrwxr-x 4 max max 4,0K Feb 11 12:14 0.1.0
drwxrwxr-x 4 max max 4,0K Feb 11 12:14 0.2.0
drwxrwxr-x 2 max max 4,0K Feb 23 14:42 0.30.0
drwxrwxr-x 2 max max 4,0K Feb 23 14:42 0.4.0
-rw-rw-r-- 1 max max   36 Sep 30 09:56 metadata.yaml
$ find services/kommander -maxdepth 1 -type d | sort | tail -1
services/kommander/0.4.0

2022-02-23 13:46 UTC, makkes commented on hack/validate-default-apps-versions.sh
> +latestKommanderVersion=$(find services/kommander -maxdepth 1 -type d | sort | tail -1)
```suggestion
latestKommanderVersion=$(find "services/kommander" -maxdepth 1 -regextype sed -regex '.*/[0-9]\+.[0-9]\+.[0-9]\+' -printf "%f\n" | sort -rV | head -1)
```

2022-02-23 13:50 UTC, makkes approved these changes

2022-02-23 13:54 UTC, merged