feat: Add dkp-insights-managment v0.1.0-rc.2
mesosphere/kommander-applications pull request #263
Opened 2022-03-25 23:28 UTC by kaiwalyajoshi

2022-03-26 01:00 UTC, takirala commented
Testing this in kommander CI via https://github.com/mesosphere/kommander/pull/1585

2022-03-26 01:02 UTC, branden requested changes
LGTM, this just needs version references bumped to reflect the new version.

2022-03-26 01:09 UTC, takirala commented
whenever this is mutated, @kaiwalyajoshi you can run @mesosphere-mergebot test all on the attached kommander PR to verify with the latest main. 

cc. @gracedo @kaiwalyajoshi @karishmagadiya do we want to create a ticket to add some tests into kommander as insights would be a default app now ?

2022-03-26 01:12 UTC, branden approved these changes

2022-03-26 01:14 UTC, kaiwalyajoshi commented
>cc. @gracedo @kaiwalyajoshi @karishmagadiya do we want to create a ticket to add some kuttl tests into kommander as insights would be a default app now ?

Yes, we have KUTTL tests that create a crashlooping pod, on an attached cluster. This should result in a CRD being created on the management cluster.

We will need the full management & attached cluster pair to do a simple verification that the e2e processing works.
Insights itself can run a gamut of e2e tests before pushing new versions to Kommander.

2022-03-26 01:28 UTC, gracedo reviewed
actually - I think it would be good to eventually get all the apps to use this kind of construct, it would make adding extra jobs and kustomization dependencies easier in the future (which we had to make use of to orchestrate upgrades that needed upgrade "hooks" which we implemented using kustomizations and dependencies). Would you be able to restructure this a bit to create a kustomization that points to the helmrelease? Essentially following the model in istio app? https://github.com/mesosphere/kommander-applications/tree/main/services/istio/1.11.6

2022-03-26 01:37 UTC, kaiwalyajoshi commented
sure, let me get that teed up.

2022-03-28 13:09 UTC, kaiwalyajoshi commented
@gracedo the latest patch reworks this PR to the istio way.

2022-03-28 13:54 UTC, kaiwalyajoshi commented
Kicked off a `kommander` build here: https://github.com/mesosphere/kommander/pull/1590

This has @gracedo latest cli commits: https://github.com/mesosphere/kommander-cli/pull/444 and this PR.

2022-03-28 16:46 UTC, gracedo approved these changes

2022-03-28 18:22 UTC, gracedo commented on services/dkp-insights-management/0.1.2/helmrelease.yaml
> +  interval: 6h
```suggestion
  interval: 6h
  retryInterval: 1m
```
actually we need this one

2022-03-28 18:47 UTC, takirala approved these changes

2022-03-28 18:48 UTC, merged