feat: bump velero v1.10.1
mesosphere/kommander-applications pull request #2724
Opened 2024-10-11 06:56 UTC by rajgitnutanix

**What problem does this PR solve?**:
Bump to
 velero/velero-plugin-for-aws:v1.10.1
**Which issue(s) does this PR fix?**:

https://jira.nutanix.com/browse/NCN-102803

2024-10-21 07:41 UTC, mhrabovcin requested changes
The relevant test from `kommander` repo is failing:

```
    logger.go:42: 06:51:10 | backup-restore/1-create-backup | starting test step 1-create-backup
    logger.go:42: 06:51:10 | backup-restore/1-create-backup | Backup:kommander/velero-test-backup created
    logger.go:42: 06:56:11 | backup-restore/1-create-backup | test step failed 1-create-backup
```

2024-10-21 10:06 UTC, rajgitnutanix commented
> The relevant test from `kommander` repo is failing:
> 
> ```
>     logger.go:42: 06:51:10 | backup-restore/1-create-backup | starting test step 1-create-backup
>     logger.go:42: 06:51:10 | backup-restore/1-create-backup | Backup:kommander/velero-test-backup created
>     logger.go:42: 06:56:11 | backup-restore/1-create-backup | test step failed 1-create-backup
> ```

Checking on the same as suggested.. Thank you..

2024-10-22 15:48 UTC, mhrabovcin commented
@rajgitnutanix can we rebase this PR on `main` and re-run the `kommander` test with velero assertions?

2024-10-23 03:25 UTC, rajgitnutanix commented
> @rajgitnutanix can we rebase this PR on `main` and re-run the `kommander` test with velero assertions?

sure will do that

2024-10-23 09:03 UTC, mhrabovcin commented on services/velero/7.1.5/defaults/cm.yaml
> +            checksumAlgorithm: "SHA256"
Can we run kommander tests with no checksum algo?
```suggestion
            checksumAlgorithm: ""
```

2024-10-23 13:55 UTC, mhrabovcin approved these changes

2024-10-23 13:55 UTC, merged