feat: Bump ai-navigator-cluster-info chart version to 0.2.9
mesosphere/kommander-applications pull request #2933
Opened 2024-12-10 09:25 UTC by rajgitnutanix

**What problem does this PR solve?**:

Bump ai-navigator-cluster-info chart version to 0.2.9
**Which issue(s) does this PR fix?**:
https://jira.nutanix.com/browse/NCN-104406

2024-12-10 14:22 UTC, alembiewski commented on licenses.d2iq.yaml
> +
```suggestion
```

2024-12-10 14:22 UTC, alembiewski commented on licenses.d2iq.yaml
> +  - container_image: docker.io/bitnami/postgresql: 15.9.0-debian-12-r0
```suggestion
  - container_image: docker.io/bitnami/postgresql:15.9.0-debian-12-r0
```

2024-12-16 07:31 UTC, alembiewski approved these changes

2024-12-16 14:26 UTC, alembiewski requested changes
l

2024-12-16 16:27 UTC, rajgitnutanix commented on services/nkp-insights/1.3.4/defaults/cm.yaml
> +        tag: 15.9.0-debian-12-r0
sure

2024-12-16 17:10 UTC, rajgitnutanix commented
> l

Done

2024-12-16 17:12 UTC, alembiewski approved these changes

2024-12-16 17:13 UTC, merged