Jabar/install kommander lifecycle chart
mesosphere/kommander-applications pull request #920
Opened 2023-01-25 19:23 UTC by Azhovan

**What problem does this PR solve?**:
make sure kommandercore helm release is installed during the cluster bootsraping 

**Which issue(s) does this PR fix?**:
https://d2iq.atlassian.net/browse/D2IQ-95250

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [ ] If the PR adds a version bump, ensure there is no breaking change in Licensing model (or NA).
- [ ] If a chart is changed or app configuration is significantly changed, the chart version is correctly incremented (so that apps are not automatically upgraded from a previous version of DKP).

2023-01-25 19:25 UTC, Azhovan commented
![image](https://user-images.githubusercontent.com/19530589/214666628-3226045f-58c0-4770-8b8e-83d4dcd5262e.png)

2023-01-25 20:23 UTC, mikolajb approved these changes

2023-01-25 20:23 UTC, mikolajb commented on kommander-lifecycle/helmrelease.yaml
> +      name: kommander
Depends on kommander?

2023-01-26 10:30 UTC, palexster approved these changes

2023-01-26 13:11 UTC, mikolajb requested changes
Blocking until we figure out how to install it in bootstrap repo step

2023-02-01 10:10 UTC, closed without merging